name: bathypy

channels:
  - conda-forge

# note that these are the developer dependencies,
# if you only want the user dependencies, see
# install_requires in setup.py
dependencies:
  - python<=3.11
  - pip
  - cartopy
  - descartes
  - earthengine-api
  - geemap
  - geojson
  - geopandas
  - geos
  - hydromt
  - ipympl
  - jupyter
  - matplotlib
  - netCDF4
#  - numba=0.54
  - numba
  - numpy>=1.23
  - pyarrow
  - pyproj
  - pytest
  - pyyaml
  - rasterio
  - requests
  - scipy
  - scikit-image
  - shapely>=2.0.0
  - tqdm
  - xarray
  - pip:
      - eepackages
      - fsspec
      - gcsfs
      - pytest_fixtures
      - geemap